version: '3'
services:
  gphoto2:
    build:
      context: .
      dockerfile: Dockerfile
    image: um/web-gphoto2
    container_name: gphoto2
    volumes:
      - ./:/src
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
